### ISSUE TITLE
gridding infrastructure

### ISSUE THREAD

**Issue by jpata** [cms-ttH/CommonClassifier#22]
As discussed by voice, we'd like to run the CommonClassifier on a common set of input ntuples using either local clusters or crab.

 I see the following subtasks:
- [x] develop a calling script that operates on the input ntuple, calls the CommonClassifier, saves the output
- [x] script that runs creates jobs (splitting) for this on a local cluster, could be based on grid-control files
- [x] submission wrapper from CRAB3 using `scriptExe` and `userInputFiles`

**Comment by kelmorab** [comment]
Hi,

regarding the MEM ouput ntuple i propose to drop the BDT value since at least the L+J BDTs are not finalized. 
And i would add all MEM output values like p_sig etc. used to calculate the final mem value. If i remember correctly this final value coud be optimized by a magic number. And by storing all the values we avoid unnessecary reruns.

**Comment by kelmorab** [comment]
Regarding the three tasks outlined above.
1) I think i could write an executable based on the mem_test.cc examples that takes the defined input ntuples and writes the output ntuples.
From looking at crab documentation i think how one could run this on custom input files.

2) I do not use gird-control. With our current batch setup it would be best to make the executable take input.root and output.root arguments.
3) For crab submission on would simply need a list of input ntuples if i understand this correctly.

The creation of the input ntuples depends on the analysis groups and their ntuples. But at least for KIT we could certainly produce ntuples in the format proposed by you.
From the crab tutorial it looks like it would be best to make the ntuples the size of the actual jobs that are run. What do you think are appropriate numbers of events? How about 100 events per job?

**Comment by jpata** [comment]
I have a prototype for this script calling CommonClassifier with input and output already finished, been testing it via crab this weekend, I'll commit tomorrow.

For both local and grid submission, we need to submit a sample with N events into chunks and propagate the chunks via a text file, that's also easy. Then each group can submit jobs based on those input files either using their own cluster or crab.

The third thing is storing the ntuples and accessing them. For crab, access via xrootd would be easiest. We need to then store the ntuples at sites with a relatively stable xrootd/storage installation and a good uptime. I would propose mirroring T2_CH_CSCS and some german site, e.g. DESY.

**Comment by kelmorab** [comment]
I just finished a similar script myself :D 
But its not tested yet. So lets go with yours for now.
But i still think that we should also store p_sig and such.
And we need to define the hypothesis IDs and systematics IDs.
We should go with what you already implemented and just document it somewhere.

The thing with the list of files is also what i understood reading the crab documentation.
Since you are already testing on crab, i assume you also have a usable crab config.
What N events do you think we should use?

For submission on the batch systems i think the main groups can handle writing submission scripts themselves. Thats usually not too difficult.

And for storage, at least for KIT and DESY the T2_DE_DESY is best.
For xrootd i think we also need to put the input files on grid storage.
In the end we then only need to collect/transfer the MEM outputs and put them in the database.

**Comment by kelmorab** [comment]
Just another thing, what name should the MEM input TTrees have?

**Comment by jpata** [comment]
@kelmorab, have a look at the script here:
https://github.com/cms-ttH/CommonClassifier/blob/master/crab/cc_looper.py

I do agree on all your points on output structure (p_sig), I'll put that in place next. For systematics and hypotheses, I'll define them in a header file using enums and we'll use the implicit int conversion.

For the moment I'm using 100 events, which results in roughly 1000 2-hour jobs for signal. However, it seems to slightly overload the T2_CH_CSCS xrootd interface, so maybe it would be better to use less jobs or try load balancing.
What's the storage protocol for DESY/KIT? Can I copy some files under `/store/user/jpata`?

**Comment by kelmorab** [comment]
The script looks good. But don't  you need to pass the hypothesis when running the MEM?
Does the mem code check whether there are enough jets and b-tags in the inputs?
Or do we have to check that manually before filling the mem trees?

1000 jobs for only for signal indeed sounds too much. 

I don't know the details of the storage. But i don't think that you can just copy files to T2_DE_DESY if that is what you mean.
Maybe we can circumvent this. What are you intending to do?

**Comment by jpata** [comment]
Actually currently the main `GetOutput` (https://github.com/cms-ttH/CommonClassifier/blob/master/interface/MEMClassifier.h#L79) method of MEMClassifier checks for itself what it should run, but it's conceivable that you want to give it explicitly. So currently the `hypo` is not used, I have to finish that script later today.

Also I didn't yet propagate the systematics.

Basically, for storage, I copied my input ntuples to
`root://storage01.lcg.cscs.ch/pnfs/lcg.cscs.ch/cms/trivcat/store/user/jpata/mem/bla.root`.
with `gsiftp`.

If I can copy to the same LFN at DESY, jobs can conceivably open the files directly from grid with load balancing.

**Comment by gvonsem** [comment]
Hi, I just have a couple of initial questions about the input MEM tree format. Sorry if I missed it somewhere.
- what is the numcalls entry of the tree, do we need to fill a certain value?
- I assume we can just fill the cMVA with a default value if we don't use it
- there is a branch of the jet type, is resolved a value 0 and boosted a value 1?
- is there already a convention of the enumeration of the systematics?

**Comment by jpata** [comment]
> what is the numcalls entry of the tree, do we need to fill a certain value?

You can fill it with -1, but it may be that we want to run MEM with a specific precision that is variable.

> I assume we can just fill the cMVA with a default value if we don't use it

Yes, though it would be good to have cMVA also available, it would be a cheap upgrade for HiggsCouplings 16!

> there is a branch of the jet type, is resolved a value 0 and boosted a value 1?

You can find the mapping here, starting from RESOLVED=0:
https://github.com/cms-ttH/CommonClassifier/blob/master/interface/MEMClassifier.h#L50

> is there already a convention of the enumeration of the systematics?

I propose this one, that I just committed: https://github.com/cms-ttH/CommonClassifier/blob/master/interface/MEMClassifier.h#L56

**Comment by jpata** [comment]
I've committed yesterday a version of the `cc_looper.py` that has the final MEM outputs. Please try it out!
