### ISSUE TITLE
vegas.c error

### ISSUE THREAD

**Issue by kelmorab** [cms-ttH/CommonClassifier#7]
Hi,

i have been trying out the ME calculation using CMSSW_7_4_15. 
I noticed that in a handful of events the MEMClassifier::GetOutput() returns a likelihood of "-nan".
In addition the following error is thrown
"Error in <GSLError>: Error 4 in vegas.c at 125 : xu must be greater than xl"

One example of this is an event with the following objects ( i assume that the ME calculation is insensitive to the choice of loose Jets)

Jets
pT, eta, phi, m, CSV
518.77 0.171288 -1.94303 49.4749 0.954083
461.506 0.780774 -2.96856 35.2939 0.931893
357.21 -1.81017 -2.6702 81.0336 0.437264
135.256 -1.505 0.84148 18.6924 0.984609
127.936 -0.333424 0.785695 15.1224 0.981502
66.6588 -1.26149 0.287357 5.65576 0.795801
45.0715 -1.46564 -2.32143 6.67862 0.118983
31.8205 1.01518 -0.135409 5.48534 0.185583
Lepton
pT, eta, phi, m, charge
147.816 -0.851258 0.780131 0.0390204 1
MET
pT, eta, phi, m
776.091 -0 0.618897 0

Best Regards,
Karim

**Comment by jpata** [comment]
Hi Karim, thanks, we'll have a look.

**Comment by jpata** [comment]
can you please also tell us the run:lumi:event triplet and which sample this is?

**Comment by kelmorab** [comment]
The sample is 
/TT_TuneCUETP8M1_13TeV-powheg-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM

and the event in question is
1:87683:8756432

**Comment by jpata** [comment]
The cause is the very high value of MET, which introduces numerical problems in finding the integral boundaries. I'll push a fix in a bit.

**Comment by hannes-kit** [comment]
Seems to have worked. Thanks!
