### ISSUE TITLE
BDT synch events

### ISSUE THREAD

**Issue by jpata** [cms-ttH/CommonClassifier#8]
@kelmorab, @hannes-kit Could you kindly provide some BDT synch events with the event:run:lumi triplet, the input objects and the final discriminant so that I can verify we get the same values on our side? Especially what concerns the categorization.

I want to do this check before submitting a larger amount of jobs later today with both discriminants.

**Comment by hannes-kit** [comment]
I am travelling to CERN today. We could synch in detail during the synchronization exercise tomorrow. Karim is currently preparing a first list with run:{inputs}:output for events from the ttH, H to bb, sample.
